### ISSUE TITLE
Dependency on epel-release-7-5.noarch.rpm fails

### ISSUE THREAD

**Issue by reinouts** [blabla1337/owasp-skf-chef#1]
`recipes/epel.rb refers` to h`ttp://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm` which returns a 404 not found.

Instead it can depend on `http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-6.noarch.rpm`

**Comment by blabla1337** [comment]
Hi Reinouts,

Thanks i have modified the source to reflect the fix.
